defaultProject: fit-aloe-417012
defaultDataset: quill_cloud
datasetSuffix: staging
defaultAssertionDataset: scribe_dashboard_reports_assertions
defaultLocation: US
vars:
  reportDataset: scribe_dashboard_reports
  translationDataset: quill_cloud_translation
  thPaymentProjects: "1029,1028"
